language: php
sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'
  - mysql -e 'GRANT ALL PRIVILEGES ON testing.* TO travis@localhost WITH GRANT OPTION;'

before_script:
  - psql -c 'create database testing;' -U postgres

install:
  - composer install

services:
  - mysql
  - postgresql

matrix:
  include:
    - php: 7.1
      env: DB_USERNAME=travis DB_PASSWORD="" DB_DATABASE="testing"
    - php: 7.1
      env: DB_USERNAME=travis DB_PASSWORD="" DB_CONNECTION=pgsql DB_PORT=5432 DB_DATABASE="testing"
    - php: 7.1
      env: DB_DATABASE=":memory:" DB_CONNECTION=sqlite
