<?php

namespace Kodilab\LaravelI18n\Tests;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Encryption\Encrypter;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Schema;
use Kodilab\LaravelI18n\Models\Locale;

abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->artisan('migrate')->run();

        $this->withFactories(dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'database/factories');

        $this->app['config']->set('app.key', 'base64:' . base64_encode(
                Encrypter::generateKey($this->app['config']->get('app.cipher'))
            ));
    }

    protected function getPackageProviders($app)
    {
        return [
            \Kodilab\LaravelI18n\I18nProvider::class
        ];
    }

    /**
     * Define environment setup.
     *
     * @param \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        $config = include 'config/config.php';

        $app['config']->set('i18n', $config);
    }
}