<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLanguagesData extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $languages = [
            [ "ISO_639_1" => "aa", "name" => "afar" ],
            [ "ISO_639_1" => "ab", "name" => "abjasio" ],
            [ "ISO_639_1" => "ae", "name" => "avéstico" ],
            [ "ISO_639_1" => "af", "name" => "afrikáans" ],
            [ "ISO_639_1" => "ak", "name" => "akano" ],
            [ "ISO_639_1" => "am", "name" => "amhárico" ],
            [ "ISO_639_1" => "an", "name" => "aragonés" ],
            [ "ISO_639_1" => "ar", "name" => "árabe" ],
            [ "ISO_639_1" => "as", "name" => "asamés" ],
            [ "ISO_639_1" => "av", "name" => "avar" ],
            [ "ISO_639_1" => "ay", "name" => "aimara" ],
            [ "ISO_639_1" => "az", "name" => "azerí" ],
            [ "ISO_639_1" => "ba", "name" => "baskir" ],
            [ "ISO_639_1" => "be", "name" => "bielorruso" ],
            [ "ISO_639_1" => "bg", "name" => "búlgaro" ],
            [ "ISO_639_1" => "bh", "name" => "bhoyapurí" ],
            [ "ISO_639_1" => "bi", "name" => "bislama" ],
            [ "ISO_639_1" => "bm", "name" => "bambara" ],
            [ "ISO_639_1" => "bn", "name" => "bengalí" ],
            [ "ISO_639_1" => "bo", "name" => "tibetano" ],
            [ "ISO_639_1" => "br", "name" => "bretón" ],
            [ "ISO_639_1" => "bs", "name" => "bosnio" ],
            [ "ISO_639_1" => "ca", "name" => "catalán" ],
            [ "ISO_639_1" => "ce", "name" => "checheno" ],
            [ "ISO_639_1" => "ch", "name" => "chamorro" ],
            [ "ISO_639_1" => "co", "name" => "corso" ],
            [ "ISO_639_1" => "cr", "name" => "cree" ],
            [ "ISO_639_1" => "cs", "name" => "checo" ],
            [ "ISO_639_1" => "cu", "name" => "eslavo" ],
            [ "ISO_639_1" => "cv", "name" => "chuvasio" ],
            [ "ISO_639_1" => "cy", "name" => "galés" ],
            [ "ISO_639_1" => "da", "name" => "danés" ],
            [ "ISO_639_1" => "de", "name" => "alemán" ],
            [ "ISO_639_1" => "dv", "name" => "maldivo" ],
            [ "ISO_639_1" => "dz", "name" => "dzongkha" ],
            [ "ISO_639_1" => "ee", "name" => "ewé" ],
            [ "ISO_639_1" => "el", "name" => "griego" ],
            [ "ISO_639_1" => "en", "name" => "inglés" ],
            [ "ISO_639_1" => "eo", "name" => "esperanto" ],
            [ "ISO_639_1" => "es", "name" => "español" ],
            [ "ISO_639_1" => "et", "name" => "estonio" ],
            [ "ISO_639_1" => "eu", "name" => "euskera" ],
            [ "ISO_639_1" => "fa", "name" => "persa" ],
            [ "ISO_639_1" => "ff", "name" => "fula" ],
            [ "ISO_639_1" => "fi", "name" => "finés" ],
            [ "ISO_639_1" => "fj", "name" => "fiyiano" ],
            [ "ISO_639_1" => "fo", "name" => "feroés" ],
            [ "ISO_639_1" => "fr", "name" => "francés" ],
            [ "ISO_639_1" => "fy", "name" => "frisón" ],
            [ "ISO_639_1" => "ga", "name" => "irlandés" ],
            [ "ISO_639_1" => "gd", "name" => "gaélico" ],
            [ "ISO_639_1" => "gl", "name" => "gallego" ],
            [ "ISO_639_1" => "gn", "name" => "guaraní" ],
            [ "ISO_639_1" => "gu", "name" => "guyaratí" ],
            [ "ISO_639_1" => "gv", "name" => "manés" ],
            [ "ISO_639_1" => "ha", "name" => "hausa" ],
            [ "ISO_639_1" => "he", "name" => "hebreo" ],
            [ "ISO_639_1" => "hi", "name" => "hindi" ],
            [ "ISO_639_1" => "ho", "name" => "hiri" ],
            [ "ISO_639_1" => "hr", "name" => "croata" ],
            [ "ISO_639_1" => "ht", "name" => "haitiano" ],
            [ "ISO_639_1" => "hu", "name" => "húngaro" ],
            [ "ISO_639_1" => "hy", "name" => "armenio" ],
            [ "ISO_639_1" => "hz", "name" => "herero" ],
            [ "ISO_639_1" => "ia", "name" => "interlingua" ],
            [ "ISO_639_1" => "id", "name" => "indonesio" ],
            [ "ISO_639_1" => "ie", "name" => "occidental" ],
            [ "ISO_639_1" => "ig", "name" => "igbo" ],
            [ "ISO_639_1" => "ii", "name" => "yi" ],
            [ "ISO_639_1" => "ik", "name" => "iñupiaq" ],
            [ "ISO_639_1" => "io", "name" => "ido" ],
            [ "ISO_639_1" => "is", "name" => "islandés" ],
            [ "ISO_639_1" => "it", "name" => "italiano" ],
            [ "ISO_639_1" => "iu", "name" => "inuktitut" ],
            [ "ISO_639_1" => "ja", "name" => "japonés" ],
            [ "ISO_639_1" => "jv", "name" => "javanés" ],
            [ "ISO_639_1" => "ka", "name" => "georgiano" ],
            [ "ISO_639_1" => "kg", "name" => "kongo" ],
            [ "ISO_639_1" => "ki", "name" => "kikuyu" ],
            [ "ISO_639_1" => "kj", "name" => "kuanyama" ],
            [ "ISO_639_1" => "kk", "name" => "kazajo" ],
            [ "ISO_639_1" => "kl", "name" => "groenlandés" ],
            [ "ISO_639_1" => "km", "name" => "camboyano" ],
            [ "ISO_639_1" => "kn", "name" => "canarés" ],
            [ "ISO_639_1" => "ko", "name" => "coreano" ],
            [ "ISO_639_1" => "kr", "name" => "kanuri" ],
            [ "ISO_639_1" => "ks", "name" => "cachemiro" ],
            [ "ISO_639_1" => "ku", "name" => "kurdo" ],
            [ "ISO_639_1" => "kv", "name" => "komi" ],
            [ "ISO_639_1" => "kw", "name" => "córnico" ],
            [ "ISO_639_1" => "ky", "name" => "kirguís" ],
            [ "ISO_639_1" => "la", "name" => "latín" ],
            [ "ISO_639_1" => "lb", "name" => "luxemburgués" ],
            [ "ISO_639_1" => "lg", "name" => "luganda" ],
            [ "ISO_639_1" => "li", "name" => "limburgués" ],
            [ "ISO_639_1" => "ln", "name" => "lingala" ],
            [ "ISO_639_1" => "lo", "name" => "lao" ],
            [ "ISO_639_1" => "lt", "name" => "lituano" ],
            [ "ISO_639_1" => "lu", "name" => "luba-katanga" ],
            [ "ISO_639_1" => "lv", "name" => "letón" ],
            [ "ISO_639_1" => "mg", "name" => "malgache" ],
            [ "ISO_639_1" => "mh", "name" => "marshalés" ],
            [ "ISO_639_1" => "mi", "name" => "maorí" ],
            [ "ISO_639_1" => "mk", "name" => "macedonio" ],
            [ "ISO_639_1" => "ml", "name" => "malayalam" ],
            [ "ISO_639_1" => "mn", "name" => "mongol" ],
            [ "ISO_639_1" => "mr", "name" => "maratí" ],
            [ "ISO_639_1" => "ms", "name" => "malayo" ],
            [ "ISO_639_1" => "mt", "name" => "maltés" ],
            [ "ISO_639_1" => "my", "name" => "birmano" ],
            [ "ISO_639_1" => "na", "name" => "nauruano" ],
            [ "ISO_639_1" => "nb", "name" => "noruego" ],
            [ "ISO_639_1" => "nd", "name" => "ndebele" ],
            [ "ISO_639_1" => "ne", "name" => "nepalí" ],
            [ "ISO_639_1" => "ng", "name" => "ndonga" ],
            [ "ISO_639_1" => "nl", "name" => "neerlandés" ],
            [ "ISO_639_1" => "nn", "name" => "nynorsk" ],
            [ "ISO_639_1" => "no", "name" => "noruego" ],
            [ "ISO_639_1" => "nr", "name" => "ndebele" ],
            [ "ISO_639_1" => "nv", "name" => "navajo" ],
            [ "ISO_639_1" => "ny", "name" => "chichewa" ],
            [ "ISO_639_1" => "oc", "name" => "occitano" ],
            [ "ISO_639_1" => "oj", "name" => "ojibwa" ],
            [ "ISO_639_1" => "om", "name" => "oromo" ],
            [ "ISO_639_1" => "or", "name" => "oriya" ],
            [ "ISO_639_1" => "os", "name" => "osético" ],
            [ "ISO_639_1" => "pa", "name" => "panyabí" ],
            [ "ISO_639_1" => "pi", "name" => "pali" ],
            [ "ISO_639_1" => "pl", "name" => "polaco" ],
            [ "ISO_639_1" => "ps", "name" => "pastú" ],
            [ "ISO_639_1" => "pt", "name" => "portugués" ],
            [ "ISO_639_1" => "qu", "name" => "quechua" ],
            [ "ISO_639_1" => "rm", "name" => "romanche" ],
            [ "ISO_639_1" => "rn", "name" => "kirundi" ],
            [ "ISO_639_1" => "ro", "name" => "rumano" ],
            [ "ISO_639_1" => "ru", "name" => "ruso" ],
            [ "ISO_639_1" => "rw", "name" => "ruandés" ],
            [ "ISO_639_1" => "sa", "name" => "sánscrito" ],
            [ "ISO_639_1" => "sc", "name" => "sardo" ],
            [ "ISO_639_1" => "sd", "name" => "sindhi" ],
            [ "ISO_639_1" => "se", "name" => "sami" ],
            [ "ISO_639_1" => "sg", "name" => "sango" ],
            [ "ISO_639_1" => "si", "name" => "cingalés" ],
            [ "ISO_639_1" => "sk", "name" => "eslovaco" ],
            [ "ISO_639_1" => "sl", "name" => "esloveno" ],
            [ "ISO_639_1" => "sm", "name" => "samoano" ],
            [ "ISO_639_1" => "sn", "name" => "shona" ],
            [ "ISO_639_1" => "so", "name" => "somalí" ],
            [ "ISO_639_1" => "sq", "name" => "albanés" ],
            [ "ISO_639_1" => "sr", "name" => "serbio" ],
            [ "ISO_639_1" => "ss", "name" => "suazi" ],
            [ "ISO_639_1" => "st", "name" => "sesotho" ],
            [ "ISO_639_1" => "su", "name" => "sundanés" ],
            [ "ISO_639_1" => "sv", "name" => "sueco" ],
            [ "ISO_639_1" => "sw", "name" => "suajili" ],
            [ "ISO_639_1" => "ta", "name" => "tamil" ],
            [ "ISO_639_1" => "te", "name" => "télugu" ],
            [ "ISO_639_1" => "tg", "name" => "tayiko" ],
            [ "ISO_639_1" => "th", "name" => "tailandés" ],
            [ "ISO_639_1" => "ti", "name" => "tigriña" ],
            [ "ISO_639_1" => "tk", "name" => "turcomano" ],
            [ "ISO_639_1" => "tl", "name" => "tagalo" ],
            [ "ISO_639_1" => "tn", "name" => "setsuana" ],
            [ "ISO_639_1" => "to", "name" => "tongano" ],
            [ "ISO_639_1" => "tr", "name" => "turco" ],
            [ "ISO_639_1" => "ts", "name" => "tsonga" ],
            [ "ISO_639_1" => "tt", "name" => "tártaro" ],
            [ "ISO_639_1" => "tw", "name" => "twi" ],
            [ "ISO_639_1" => "ty", "name" => "tahitiano" ],
            [ "ISO_639_1" => "ug", "name" => "uigur" ],
            [ "ISO_639_1" => "uk", "name" => "ucraniano" ],
            [ "ISO_639_1" => "ur", "name" => "urdu" ],
            [ "ISO_639_1" => "uz", "name" => "uzbeko" ],
            [ "ISO_639_1" => "ve", "name" => "venda" ],
            [ "ISO_639_1" => "vi", "name" => "vietnamita" ],
            [ "ISO_639_1" => "vo", "name" => "volapük" ],
            [ "ISO_639_1" => "wa", "name" => "valón" ],
            [ "ISO_639_1" => "wo", "name" => "wolof" ],
            [ "ISO_639_1" => "xh", "name" => "xhosa" ],
            [ "ISO_639_1" => "yi", "name" => "yídish" ],
            [ "ISO_639_1" => "yo", "name" => "yoruba" ],
            [ "ISO_639_1" => "za", "name" => "chuan" ],
            [ "ISO_639_1" => "zh", "name" => "chino" ],
            [ "ISO_639_1" => "zu", "name" => "zulú" ]
        ];

        foreach ($languages as $language)
        {
            DB::table(config('i18n.language.table'))->insert([
                'name' => $language["name"],
                'ISO_639_1' => $language["ISO_639_1"],
                'enabled' => false,
                'default' => false
            ]);
        }

        DB::table(config('i18n.language.table'))->where('ISO_639_1', config('app.locale'))->update([
            'enabled' => true,
            'default'=> true
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table(config('i18n.language.table'))->delete();
    }
}
