<?php


namespace Kodilab\LaravelI18n\Tests\Unit\Translations;


use Illuminate\Foundation\Testing\WithFaker;
use Kodilab\LaravelI18n\Models\Locale;

class TestCase extends \Kodilab\LaravelI18n\Tests\TestCase
{
    /** @var string */
    protected $lang_path;

    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->lang_path = $this->resources_path . DIRECTORY_SEPARATOR . 'lang';
        $this->createLangDirectory();
    }

    protected function tearDown(): void
    {
        $this->removeLangDirectory();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function createLangDirectory()
    {
        if (!is_dir($this->lang_path)) {
            $this->filesystem->makeDirectory($this->lang_path, 0755, true);
        }
    }

    private function removeLangDirectory()
    {
        if (is_dir($this->lang_path)) {
            $this->filesystem->deleteDirectory($this->lang_path);
        }
    }

    /**
     * Add a raw translation array to the file
     *
     * @param string $path
     * @param array $translations
     */
    protected function addTranslationsToFile(string $path, array $translations)
    {
        $translations_json = json_encode($translations, JSON_PRETTY_PRINT);

        file_put_contents($path, $translations_json);
    }

    /**
     * Add random raw translations to the file
     *
     * @param string $path
     * @param int $count
     */
    protected function fillFileWithRandomTranslations(string $path, int $count = 10)
    {
        $translations = [];

        for ($i = 0; $i < $count; $i ++) {
            $translations[$this->faker->unique()->paragraph] = $this->faker->paragraph;
        }

        $this->addTranslationsToFile($path, $translations);
    }

    /**
     * Returns the json file path for the given locale
     *
     * @param Locale $locale
     * @return string
     */
    protected function getJSONPathFromLocale(Locale $locale)
    {
        return $this->lang_path . DIRECTORY_SEPARATOR . $locale->reference . '.json';
    }
}