<?php

namespace Kodilab\LaravelI18n\Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Kodilab\LaravelI18n\Facade;
use Kodilab\LaravelI18n\Models\Locale;
use Kodilab\LaravelI18n\Tests\TestCase;

class CreateLocaleTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->generateFallbackLocale();

        $this->generateFallbackLocale();

        Facade::editorRoutes();
    }

    public function test_create_form()
    {
        $this->get(route('i18n.locales.create'))->assertStatus(200);
    }
}
