<?php

namespace Kodilab\LaravelI18n\Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Kodilab\LaravelI18n\Facade;
use Kodilab\LaravelI18n\Tests\TestCase;

class DashboardTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Facade::editorRoutes();
    }

    public function test_dashboard_is_working()
    {
        $this->get(route('i18n.dashboard'))->assertStatus(200);
    }
}