<?php


namespace Kodilab\LaravelI18n\Tests\Unit\Commands\Generators;


use Illuminate\Foundation\Testing\WithFaker;
use Kodilab\LaravelI18n\Models\Locale;
use Kodilab\LaravelI18n\Tests\TestCase;
use Symfony\Component\Finder\SplFileInfo;

class FallbackTest extends TestCase
{
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Locale::getFallbackLocale()->delete();
    }

    public function test_generates_the_fallback_locale()
    {
        $this->artisan('i18n:fallback')->run();

        $this->assertNotNull(Locale::getFallbackLocale());
    }

    public function test_generates_the_fallback_locale_based_on_the_laravel_configuration()
    {
        $data = factory(Locale::class)->make();

        $this->app['config']->set('app.fallback_locale', $data->name);

        $this->artisan('i18n:fallback')->run();

        $this->assertEquals($data->name, Locale::getFallbackLocale()->name);
    }
}