<?php

namespace Kodilab\LaravelI18n;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Kodilab\LaravelFilters\Filterable;
use Kodilab\LaravelI18n\Exceptions\MissingLanguageException;

class Translation extends Model
{

    use Filterable;

    protected $table;

    protected $fillable = ['translation', 'language_id', 'md5', 'text_id', 'needs_revision'];

    protected $casts = [
        'md5' => 'string',
        'translation' => 'string',
        'language_id' => 'integer',
        'text_id' => 'integer',
        'needs_revision' => 'boolean'
    ];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = config('i18n.tables.translations');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saved(function (Translation $translation) {
            $language = $translation->language;

            Cache::forget($language->reference . '_' . $translation->md5);
        });
    }

    //relationships

    public function language()
    {
        return $this->belongsTo(Language::class, 'language_id');
    }

    public function text()
    {
        return $this->belongsTo(Text::class, 'text_id');
    }

    //scope methods

    // methods
    /**
     * Returns whether the translation exists for the language $language
     * @param $md5
     * @param Language $language
     * @return bool
     */
    public static function existsTranslation($md5, Language $language)
    {
        return !is_null(Translation::where('md5', $md5)->where('language_id', $language->id)->first());
    }

    /**
     * Stores in database a new translation text $text for the fallback language.
     * @param $md5
     * @param $text
     * @param Language|null $language
     * @throws MissingLanguageException
     */
    public static function generateFallbackTranslation($text)
    {
        $fallback_language = Language::getFallbackLanguage();
        $md5 = md5($text);

        if (!self::existsTranslation($md5, $fallback_language))
        {
            $translation = Translation::create([
                'translation' => $text,
                'md5' => $md5,
                'language_id' => $fallback_language->id
            ]);

            session()->forget('fallback_language');

        }

        return $translation;
    }

    /**
     * Returns the translation of $text in $language language. If it doesn't exists, try to create it for the fallback language
     * @param $md5
     * @param $language
     * @return mixed|null
     * @throws MissingLanguageException
     */
    public static function getTranslationByText(string $text, Language $language)
    {
        $md5 = md5($text);

        $translation = self::getTranslationByMd5($md5, $language);

        if(!is_null($translation))
        {
            return $translation;
        }

        self::generateFallbackTranslation($text);

        return null;
    }

    public static function getTranslationByMd5(string $md5, Language $language)
    {

        /** @var Translation $translation */
        $translation = Translation::where('md5', $md5)->where('language_id', $language->id)->first();

        if(!is_null($translation))
        {
            return $translation;
        }

        return null;
    }

    public static function getLanguageTranslations(Language $language)
    {
        return Translation::where('language_id', $language)->get();
    }
}
