<?php


namespace Kodilab\LaravelI18n\Tests\Unit;


use Kodilab\LaravelI18n\Models\Locale;
use Kodilab\LaravelI18n\Tests\TestCase;
use Kodilab\LaravelI18n\Translations\Installer;

class InstallerTest extends TestCase
{
    /** @var Locale */
    protected $locale;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->locale = $this->fallback_locale;
        $this->copyLaravelTranslationFilesToResources();
    }

    public function test_true()
    {
        $installer = new Installer($this->locale);

        //TODO: Add tests

        $this->assertTrue(true);
    }

    private function copyLaravelTranslationFilesToResources()
    {
        $this->filesystem->copyDirectory(resource_path('lang'), $this->resources_path . DIRECTORY_SEPARATOR . 'lang');
    }
}