<?php

namespace Kodilab\LaravelI18n\Tests\Unit;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Kodilab\LaravelI18n\Linguist;
use Kodilab\LaravelI18n\Models\Locale;
use Kodilab\LaravelI18n\Models\Text;
use Kodilab\LaravelI18n\Models\Translation;
use Kodilab\LaravelI18n\Tests\TestCase;

class LinguistTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    /** @var Linguist */
    protected $linguist;

    protected $filesystem;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->filesystem = $this->app->make(Filesystem::class);

        $this->linguist = new Linguist($this->filesystem, [$this->test_files_path]);

    }
}
