<?php

namespace Kodilab\LaravelI18n\Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Kodilab\LaravelI18n\Models\Locale;
use Kodilab\LaravelI18n\Models\Text;
use Kodilab\LaravelI18n\Models\Translation;
use Kodilab\LaravelI18n\Tests\TestCase;

class TextTest extends TestCase
{
    /** @var Text */
    protected $text;

    use RefreshDatabase;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        //For some reason, RefreshDatabase trait isn't working as expected in MySQL. So we remove all locales manually.
        Text::all()->each(function ($item) {
            $item->delete();
        });

        $this->text = factory(Text::class)->create();
    }

    public function test_a_new_text_generate_a_fallback_locale_translation()
    {
        $text = factory(Text::class)->create();

        $fallback_locale = Locale::getFallbackLocale();

        $translation = Translation::where('md5', $text->md5)->where('locale_id', $fallback_locale->id)->get()->first();

        $this->assertNotNull($translation);
        $this->assertEquals($translation->md5, $text->md5);
        $this->assertEquals($translation->translation, $text->text);
        $this->assertEquals($fallback_locale->id, $translation->locale->id);
    }
}
